version: '3.8'

services:
  fastapi:
    build: ./backend
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - mynetwork
    entrypoint: ["/app/docker-entrypoint.sh"]

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork: