"""add player_stats table

Revision ID: 8ed7ef9c4951
Revises: ade95afcb7b4
Create Date: 2025-10-11 23:23:36.126334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed7ef9c4951'
down_revision: Union[str, None] = 'ade95afcb7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wg_player_id', sa.Integer(), nullable=False),
    sa.Column('computed_battles', sa.Integer(), nullable=False),
    sa.Column('player_battles', sa.Integer(), nullable=False),
    sa.Column('wn8', sa.Float(), nullable=False),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wg_player_id'], ['players.wg_player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_stats')
    # ### end Alembic commands ###
