"""Initial migration

Revision ID: ade95afcb7b4
Revises: 
Create Date: 2025-02-18 17:43:52.446104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade95afcb7b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=24), nullable=False),
    sa.Column('wg_player_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wg_player_id')
    )
    op.create_table('tanks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nation', sa.String(length=100), nullable=False),
    sa.Column('wg_tank_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('exp_def', sa.Float(), nullable=True),
    sa.Column('exp_spot', sa.Float(), nullable=True),
    sa.Column('exp_damage', sa.Float(), nullable=True),
    sa.Column('exp_winrate', sa.Float(), nullable=True),
    sa.Column('exp_frag', sa.Float(), nullable=True),
    sa.Column('small_icon', sa.String(), nullable=True),
    sa.Column('contour_icon', sa.String(), nullable=True),
    sa.Column('big_icon', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wg_tank_id')
    )
    op.create_table('vehicles_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wg_player_id', sa.Integer(), nullable=False),
    sa.Column('wg_tank_id', sa.Integer(), nullable=False),
    sa.Column('tank_battles', sa.Integer(), nullable=False),
    sa.Column('tank_wn8', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('actual', sa.Boolean(), nullable=False),
    sa.Column('avg_damage', sa.Float(), nullable=True),
    sa.Column('avg_spot', sa.Float(), nullable=True),
    sa.Column('avg_frag', sa.Float(), nullable=True),
    sa.Column('avg_def', sa.Float(), nullable=True),
    sa.Column('avg_winrate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['wg_player_id'], ['players.wg_player_id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['wg_tank_id'], ['tanks.wg_tank_id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles_stats')
    op.drop_table('tanks')
    op.drop_table('players')
    # ### end Alembic commands ###
