"""Initial migration

Revision ID: d1e0d8a396d0
Revises: 
Create Date: 2025-02-04 10:54:29.692090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e0d8a396d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tanks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nation', sa.String(length=100), nullable=False),
    sa.Column('wg_tank_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('exp_def', sa.Float(), nullable=True),
    sa.Column('exp_spot', sa.Float(), nullable=True),
    sa.Column('exp_damage', sa.Float(), nullable=True),
    sa.Column('exp_winrate', sa.Float(), nullable=True),
    sa.Column('exp_frag', sa.Float(), nullable=True),
    sa.Column('small_icon', sa.String(), nullable=True),
    sa.Column('contour_icon', sa.String(), nullable=True),
    sa.Column('big_icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wg_tank_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tanks')
    # ### end Alembic commands ###
