"""Initial migration

Revision ID: ed2ed8bcd46e
Revises: 367e24d5b6a7
Create Date: 2025-01-30 15:05:57.765491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2ed8bcd46e'
down_revision: Union[str, None] = '367e24d5b6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tanks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nation', sa.String(length=100), nullable=False),
    sa.Column('wg_tank_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('exp_def', sa.Float(), nullable=True),
    sa.Column('exp_spot', sa.Float(), nullable=True),
    sa.Column('exp_damage', sa.Float(), nullable=True),
    sa.Column('exp_winrate', sa.Float(), nullable=True),
    sa.Column('exp_frag', sa.Float(), nullable=True),
    sa.Column('small_icon', sa.String(), nullable=True),
    sa.Column('contour_icon', sa.String(), nullable=True),
    sa.Column('big_icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wg_tank_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tanks')
    # ### end Alembic commands ###
